import React, {Component} from 'react';
import Modal from 'react-bootstrap/Modal';
import './map.css'

class Map extends Component {
    render() {
        return (
            <Modal show={this.props.displayMap} onHide={this.props.closeMap} dialogClassName={'modal-90w'} centered>

                <Modal.Body>
                </Modal.Body>

                <Modal.Footer>
                    <h3>INVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORYINVENTORY</h3>
                </Modal.Footer>

            </Modal>
        )
    }
}

export default Map;